'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Online_TV.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property abolatv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abolatv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property aljazeera() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aljazeera", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property axn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("axn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property axnblack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("axnblack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property axnwhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("axnwhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property band() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("band", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bandsports() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bandsports", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bbcworldnews() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bbcworldnews", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property benficatv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("benficatv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bloomberg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bloomberg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property canalpanda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("canalpanda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cartoonnetwork() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cartoonnetwork", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chelseatv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chelseatv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property discovery() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("discovery", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property discoveryturbo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("discoveryturbo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property disney() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disney", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property disneyjunior() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disneyjunior", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property economicotv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("economicotv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property espn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("espn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property espnamerica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("espnamerica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property espnbrasil() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("espnbrasil", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property euronews() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("euronews", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eurosport() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eurosport", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eurosport2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eurosport2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fashiontv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fashiontv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property foxcrime() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("foxcrime", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property foxlife() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("foxlife", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property foxmovies() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("foxmovies", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property france24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("france24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fueltv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fueltv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property historia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("historia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hollywood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hollywood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property motorstv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("motorstv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mov() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mov", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mtv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mtv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nationalgeographic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nationalgeographic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nickelodeon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nickelodeon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property odisseia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("odisseia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pandabiggs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pandabiggs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pfc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pfc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pokerchannel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pokerchannel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property portocanal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portocanal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property record() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("record", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rtp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rtp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rtp2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rtp2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rtpacores() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rtpacores", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rtpinformacao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rtpinformacao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rtpinternacional() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rtpinternacional", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rtpmadeira() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rtpmadeira", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rtpmemoria() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rtpmemoria", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rtpolimpicos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rtpolimpicos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sbt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sbt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sickids() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sickids", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sicmulher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sicmulher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sicnoticias() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sicnoticias", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sicradical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sicradical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skynews() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skynews", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skypoker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skypoker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skysports() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skysports", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skysports2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skysports2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sporttv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sporttv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sporttv2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sporttv2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sporttv2alternativa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sporttv2alternativa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sporttv3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sporttv3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sporttv4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sporttv4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sporttvalternativa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sporttvalternativa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sportv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sportv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property syfy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("syfy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tlc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tlc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tvglobo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tvglobo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tvi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tvi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tvi24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tvi24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vh1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vh1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property xxx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xxx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
