Public Module modVAR
    Public Headers As String = "Referer: http://www.televisaofutebol.com"

    Public sporttv As String = "http://www.televisaofutebol.com/iframe.php?chname=sporttv"
    Public sporttv2 As String = "http://www.televisaofutebol.com/iframe.php?chname=sporttv2"
    Public sporttv3 As String = "http://www.televisaofutebol.com/iframe.php?chname=sporttv3"
    Public sporttv4 As String = "http://www.televisaofutebol.com/iframe.php?chname=sporttv4"

    Public sic As String = "http://www.televisaofutebol.com/iframe.php?chname=sic"

    Public sicnoticias As String = ""
    Public sicradical As String = "http://www.casti.tv/embed.php?v=sicrra&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public sicmulher As String = "http://www.casti.tv/embed.php?v=sicmulher11ssaa&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public sickids As String = "http://www.casti.tv/embed.php?v=tsicki&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public tvi As String = "http://www.casti.tv/embed.php?v=ttvi6&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public tvilive As String = "http://www.casti.tv/embed.php?v=ttvi6&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public tvi24 As String = "http://www.abclive.tv/embed.php?u=ttvi242&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public rtp As String = "http://www.casti.tv/embed.php?v=trtp&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public rtp2 As String = ""
    Public rtpolimpicos As String = ""
    Public rtpinformacao As String = ""
    Public rtpmemoria As String = ""
    Public rtpinternacional As String = ""
    Public rtpacores As String = ""
    Public rtpmadeira As String = ""
    Public benficatv As String = ""
    Public abolatv As String = ""
    Public portocanal As String = "http://www.abclive.tv/embed.php?u=rafa7&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public chelseatv As String = ""
    Public axn As String = "http://www.televisaofutebol.com/iframe.php?chname=axn"
    Public axnblack As String = "http://www.casti.tv/embed.php?v=taxnb&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public axnwhite As String = "http://www.casti.tv/embed.php?v=axnwhitea&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public syfy As String = "http://www.casti.tv/embed.php?v=tsyfy&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public fox As String = "http://www.televisaofutebol.com/iframe.php?chname=fox"
    Public foxlife As String = "http://www.casti.tv/embed.php?v=tfxl&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public foxmovies As String = "http://www.casti.tv/embed.php?v=tfxm&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public foxcrime As String = "http://www.casti.tv/embed.php?v=tfxc&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public hollywood As String = "http://www.casti.tv/embed.php?v=tholy&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public mov As String = "http://www.casti.tv/embed.php?v=mova&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public mtv As String = "http://www.casti.tv/embed.php?v=tmtv&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public vh1 As String = "http://www.casti.tv/embed.php?v=tvh2&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public fashiontv As String = ""
    Public fueltv As String = "http://www.casti.tv/embed.php?v=tfuel&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public motorstv As String = "http://www.casti.tv/embed.php?v=tmoto&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public tlc As String = ""
    Public discoveryturbo As String = ""
    Public discovery As String = "http://www.casti.tv/embed.php?v=tdisc&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public odisseia As String = "http://www.casti.tv/embed.php?v=todi&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public historia As String = "http://www.casti.tv/embed.php?v=thist&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public nationalgeographic As String = "http://www.casti.tv/embed.php?v=tnatg&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public disney As String = "http://www.casti.tv/embed.php?v=tdis&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public disneyjunior As String = ""
    Public canalpanda As String = "http://www.casti.tv/embed.php?v=tpanda&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public pandabiggs As String = "http://www.casti.tv/embed.php?v=tpandabi&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public nickelodeon As String = ""
    Public cartoonnetwork As String = ""
    Public tvglobo As String = ""
    Public record As String = ""
    Public sbt As String = ""
    Public band As String = ""
    Public bandsports As String = ""
    Public pfc As String = ""
    Public sportv As String = ""
    Public france24 As String = ""
    Public euronews As String = ""
    Public bbcworldnews As String = ""
    Public rt As String = ""
    Public aljazeera As String = ""
    Public skynews As String = ""
    Public skypoker As String = ""
    Public pokerchannel As String = ""
    Public skysports2 As String = ""
    Public espnamerica As String = "http://www.casti.tv/embed.php?v=tespna&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public espn As String = ""
    Public espnbrasil As String = ""
    Public eurosport As String = "http://www.casti.tv/embed.php?v=teuro&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public eurosport2 As String = "http://www.casti.tv/embed.php?v=euro222sa&vw=650&vh=500&domain=www.televisaofutebol.com"
    Public economicotv As String = ""
    Public bloomberg As String = ""


End Module
